package org.jspresso.hrsample.model.extension;

import org.jspresso.framework.model.component.AbstractComponentExtension;

import org.jspresso.hrsample.model.Company;

/**
 * Generated by Jspresso Developer Studio
 */
public class CompanyExtension extends AbstractComponentExtension<Company> {

	public CompanyExtension(Company component) {
		super(component);

		registerNotificationForwarding(component, Company.EMPLOYEES, Company.WORKFORCE);
	}

  /**
   * generated by Jspresso Developer Studio
   * 
   * @return
   */
  public Integer getWorkforce() {
    Company company = getComponent();
    return company.getEmployees().size();
  }
  
}
