/*
 * Generated by Jspresso. All rights reserved.
 */
package org.jspresso.hrsample.model;

/**
 * Event entity.
 * <p>
 * Generated by Jspresso. All rights reserved.
 * <p>
 *
 * @hibernate.mapping
 *           default-access = "org.jspresso.framework.model.persistence.hibernate.property.EntityPropertyAccessor"
 * @hibernate.class
 *           table = "EVENT"
 *           dynamic-insert = "true"
 *           dynamic-update = "true"
 *           persister = "org.jspresso.framework.model.persistence.hibernate.entity.persister.EntityProxyJoinedSubclassEntityPersister"
 * @author Generated by Jspresso
 * @version $LastChangedRevision$
 */
public interface Event extends
  org.jspresso.hrsample.model.Traceable,
  org.jspresso.framework.model.entity.IEntity {

  /**
   * @hibernate.id generator-class = "assigned" column = "ID" type = "string"
   *               length = "36"
   * <p>
   * {@inheritDoc}
   */
  java.io.Serializable getId();

  /**
   * @hibernate.version column = "VERSION" unsaved-value = "null"
   * <p>
   * {@inheritDoc}
   */
  Integer getVersion();

  /**
   * Gets the text.
   *
   * @hibernate.property
   * @hibernate.column
   *           name = "TEXT"
   *           length = "2048"
   * @return the text.
   */
  java.lang.String getText();

  /**
   * Sets the text.
   *
   * @param text
   *          the text to set.
   */
  void setText(java.lang.String text);

}
